name: AdvancedHomes
version: '${project.version}'
main: com.soyadrianyt001.advancedhomes.AdvancedHomes
api-version: '1.21'
description: Premium Advanced Homes Plugin - by soyadrianyt001
author: soyadrianyt001
softdepend:
  - PlaceholderAPI

commands:
  ahome:
    description: Teleporta a tu hogar
    usage: /ahome [nombre]
    aliases: [ah]
  ahome create:
    description: Crea un hogar
    usage: /ahome create [nombre]
  ahome remove:
    description: Elimina un hogar
    usage: /ahome remove <nombre>
  ahome list:
    description: Lista tus hogares
    usage: /ahome list
  ahome gui:
    description: Abre el menu
    usage: /ahome gui
  ahomes:
    description: Comando admin
    usage: /ahomes <reload|info|reset>

permissions:
  advancedhomes.home:
    default: true
  advancedhomes.sethome:
    default: true
  advancedhomes.delhome:
    default: true
  advancedhomes.homes:
    default: true
  advancedhomes.gui:
    default: true
  advancedhomes.admin:
    default: op
  advancedhomes.homes.others:
    default: op
  advancedhomes.bypass.cooldown:
    default: op
  advancedhomes.bypass.limit:
    default: op
  advancedhomes.limit.vip:
    default: false
  advancedhomes.limit.premium:
    default: false
  advancedhomes.limit.unlimited:
    default: false
  advancedhomes.reload:
    default: op
  advancedhomes.reset:
    default: op
